# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=80)),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=80)),
            ],
        ),
    ]
